
# ================================================
# DO NOT EDIT THIS FILE
# ================================================
from .game import TicTacToe
from .tree import Node
from .mcts import mcts
def play_game(model1, model2, sims=50):
    env = TicTacToe()  # start new game
    models = {1: model1, -1: model2}  # map player to model

    while env.winner() is None:
        root = Node(env.clone()) # create root node for MCTS
        move = mcts(root, models[env.current_player], n_simulations=sims)
        # move is determined by MCTS
        env.play(move) # update game with chosen move

    return env.winner()  # return final winner
