# ================================================
# DO NOT EDIT THIS FILE
# ================================================
import math
class Node:
    def __init__(self, state, parent=None):
        # Each Node represents a game state in the search tree
        self.state = state       # current game state (TicTacToe)
        self.parent = parent     # parent node in the tree
        self.children = {}       # dict of move:index -> Node
        self.visits = 0          # number of times this node was visited
        self.value = 0.0         # cumulative value from simulations

    def is_leaf(self):
        # Returns True if the node has no children
        # Leaf nodes are expanded during MCTS
        return len(self.children) == 0

    def ucb_score(self, child, c=1.4):
        # Upper Confidence Bound for Trees
        # Balances exploitation (value/visits) and exploration
        if child.visits == 0:
            return float("inf")   # force visiting unvisited nodes
        return (child.value / child.visits +
                c * math.sqrt(math.log(self.visits) / child.visits))

    def best_child(self, c=1.4):
        # Select child with highest UCB score
        # Used during selection phase of MCTS
        return max(self.children.values(), key=lambda child: self.ucb_score(child, c))
